# Generated by Django 5.2 on 2025-05-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
    ]
