# Generated by Django 5.2 on 2025-05-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
